# Generated by Django 5.2.1 on 2025-05-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="new/"),
        ),
    ]
